### ISSUE TITLE
Is there a way to show all the article categories, not only those that are on the first page?

### ISSUE THREAD

**Issue by SerhiiVynohradov** [templaza/tz_portfolio_old#23]
I'm using tz portfolio.
And it's great!

The only thing I can't figure out:
There are over 60 articles, and I want to show only 10 unless they click "add item more".
But the problem is that it shows only categories of those first 10.
So that even after they click to display more articles, new categories don't show up.

Is that normal? Or am I missing some settings?

**Comment by templaza** [comment]
Hi, 

If you click "add item more" the system will load more 10 items and if they belongs to another category. Then it will be loaded on portfolio page.

Best Regards,
Sonle

**Comment by SerhiiVynohradov** [comment]
Thanks!
Btw is it possible to change text "Add item more" to something else?

**Comment by templaza** [comment]
Yes, You can change it in language file https://github.com/templaza/tz_portfolio/blob/master/site/languages/en-GB/en-GB.com_tz_portfolio.ini
Line 21: COM_TZ_PORTFOLIO_ADD_ITEM_MORE="Add item more"
You can change it to something else.

Best Regards,
Sonle

**Comment by SerhiiVynohradov** [comment]
Great, thanks again!
One more question.
When I click on the picture in portfolio and it opens in the modal - there are a lot of links from external sources.
Most of them have ipsum lorem text.
Can I turn off those links?

**Comment by SerhiiVynohradov** [comment]
Sorry for bothering but my main question was if I can reload the list of categories when I click "add item more".
Or if it's possible to show all categories right away, even if related articles are not in the list of first 10.
So far when I click "add item more" and new pics belong to different category - list of categories to filter by stays unchanged.

**Comment by trinhvanduong** [comment]
When you click "Add item more", the new categories will insert to the filter layout. And you can show all categories filter by going to item " Show All Filter" in global config
