### ISSUE TITLE
Filtered by CATEGORY links don't show all articles

### ISSUE THREAD

**Issue by whynotadv** [templaza/tz_portfolio_old#26]
Not sure what is going on and if this is a glitch but I have chosen to filter my articles by category but when I click on the category text next to "show all" only 3 or 4 articles show up instead of the max of 15 that I have set. 

 For example: clicking "screen printing" from the home page and you'll see I only get 3 articles to show but if you go under products and select screen printing in the main menu it then shows all 15 of the screen printing articles perfectly. So what is wrong????

You can see it in action here:
http://whyknottmanager.com/dgiwebsite/

**Comment by templaza** [comment]
Because in the homepage you choose multi-category. So TZ Portfolio show only 15 article in all of your categories. If you want to show all item in home page you should configure article limit higher than 15. I suggest 30 or 40. 
You can configure it in Menu Configuration.

Best Regards,
Sonle

**Comment by whynotadv** [comment]
I don't want to show all items initially. What I mean is this...On the home page you'll notice next to the "show all" link at the top there are other categories present. When you click on those categories from the home page it only shows 4 or 3 from each when the category link is clicked. I want those category links to show the 15 articles from their prospective categories not just the ones present in the initially loaded 15 on the home page. I don't want to show 30 or 40 as that significantly slows down page load time. Also makes the page longer. I think it should automatically recognize that you specified 15 articles from each category to show up and when the category links are clicked it shows those 15. With infinite scroll if I scroll to allow all of the articles to load THEN I can click the category links at the top and it shows the 15 articles from each category. I guess short of loading a small horizontal menu above the main content area and loading each category that way there is nothing else I can do other than to load ALL articles instead of giving a limit of 15????

Also I think if people visit my clients home page and see an initial 15 articles and (not scroll down) and try clicking SHOW ALL and it doesn't do anything and also if they click a category and only 3 or 4 show up they might feel like dgi creative doesn't offer much. Not sure what to do, I'd rather not slow page load time down and my client likes 3 rows of 5. Maybe in article categories you could add an article limit feature?

**Comment by templaza** [comment]
Thanks for your suggest. Unfortunately, This feature is not available in current version of TZ Portfolio. We will consider to a solution to allows script auto loading other articles in a category when use click filter. 

Thanks and Best Regards,
Sonle

**Comment by whynotadv** [comment]
Sonie,
Thanks for reading through my issue and considering it for the next version! Have a good one and thanks again for your awesome support!

Kindly,
Kenny

**Comment by whynotadv** [comment]
Hi Sonie,

Is there a way to begin with a specific category instead of the show all? Like on my "Screen Printing" page I want to initially load the 15 screen printing articles but still have the show all and other categories there to click on.
The way its setup now if I add other categories and turn on the show all filter it doesn't load the actual screen printing category articles first. Your help would be extremely appreciated.

Here is my current page:
http://dgicreative.com/index.php/products/screen-printing

Thanks,
Kenny

---

Kenny Berwager
Art Director
Whyknott Advertising
1204 High St., Hanover 
PA 17331
Ph: 717.630.1240
Fx:  717.630.1277
http://www.whyknott.com
