### ISSUE TITLE
Error message on clicking to edit article on backend

### ISSUE THREAD

**Issue by Alyks** [templaza/tz_portfolio_old#42]
Last version of TZ Portfolio 3.1.6
Last version of Joomla 3.1.5

I'v got this message error whenever i click to create or edit a joomla article (com_content)

`View not found [name, type, prefix]:, html, tz portfolio View`

![52715250ec8d8358f400003f](https://f.cloud.github.com/assets/5816416/1439973/b5ee0b6a-4192-11e3-96b4-8081271bf8e8.jpeg)

Very very huge issue !

**Comment by Alyks** [comment]
The error message texte : "500 : View not found [name, type, prefix]: tz_portfolio, html, tz_portfolioView"

**Comment by Alyks** [comment]
The post on the develloper website : http://www.templaza.com/Configuration-and-Use/5416-TZ-Portfolio-Error-When-Opening-Content/Page-2.html

**Comment by trinhvanduong** [comment]
Hi,
Your problem was fixed in version 3.1.7. Please update it.
Thanks

**Comment by Alyks** [comment]
Perfect. It's working now with this fixed version. Thanks !
