### ISSUE TITLE
improperly escaped $row->attachtitle

### ISSUE THREAD

**Issue by Boldairdev** [templaza/tz_portfolio_old#59]
escapes the echo of $row->attachtitle with htmlentities() to avoid breaking the javascript when the string contains a single quote(') character.

Note, if an attachtitle has been stored with a single quote, the whole page javascript will break, and it will become impossible to even close the edited article.

here is a patch that solves it :
diff --git a/admin/views/article/tmpl/edit.php b/admin/views/article/tmpl/edit.php
index 8f3f137..091f9b2 100644
--- a/admin/views/article/tmpl/edit.php
+++ b/admin/views/article/tmpl/edit.php
@@ -1021,12 +1021,12 @@ if(COM_TZ_PORTFOLIO_JVERSION_COMPARE){
                     value:'<?php echo $row -> attachold;?>'
                 }).inject(myTd);
                 var myTd = new Element('td',{
-                    html:'<?php echo !empty($row -> attachtitle)? $row -> attachtitle: $row -> attachold;?>'
-                    html:'<?php echo !empty($row -> attachtitle)? htmlentities($row -> attachtitle,ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE | ENT_DISALLOWED,"UTF-8",false): htmlentities($row -> attachold, ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE | ENT_DISALLOWED, "UTF-8", false);?>'
               }).inject(myTr);
               var myHidden = new Element('input',{
                   type:'hidden',
                   name:'tz_attachments_hidden_title[]',
-                    value:'<?php if($row -> attachfiles != $row -> attachtitle) echo $row -> attachtitle;?>'
-                    value:'<?php if($row -> attachfiles != $row -> attachtitle) echo htmlentities($row -> attachtitle,ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE | ENT_DISALLOWED,"UTF-8",false) ;?>'
               }).inject(myTd);
               var myTd = new Element('td',{
               }).inject(myTr);

**Comment by templaza** [comment]
Thanks Boldairdev,
I have merged master brand! :)
Thanks for contributing.
Best Regards,
Sonny

**Comment by Boldairdev** [comment]
```
Hi, Thanks,
    I'm afraid I had forgotten a field just above the ones i had
    escaped.
    I made the correction and sent a pull request (#61)
    Regards

    Eric
        Bouquerel 74 rue de la Fédération 
        75015 Paris - France.
    Téléphone : 
          01
              71 18 19 03
        Fax : 
          01
              71 18 19 19

  Le 06/10/2014 05:45, TemPlaza a écrit :

  Thanks Boldairdev,
    I have merged master brand! :)
    Thanks for contributing.
    Best Regards,
    Sonny 
  —
    Reply to this email directly or view
      it on GitHub.
  {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/templaza/tz_portfolio/issues/59#issuecomment-57972463">"https://github.com/templaza/tz_portfolio/issues/59#issuecomment-57972463"</a>,"name":"View Issue"}}
```
