### ISSUE TITLE
Strict Standards - nothing crucial

### ISSUE THREAD

**Issue by ntcreation** [templaza/tz_portfolio_old#7]
With latest verison of PHP

Strict Standards: Only variables should be assigned by reference in /public_html/dev/plugins/system/tz_portfolio/tz_portfolio.php on line 28

Strict Standards: Only variables should be assigned by reference in /public_html/dev/plugins/system/tz_portfolio/tz_portfolio.php on line 63

**Comment by whynotadv** [comment]
I dowloaded the most recent tz portfolio 3.0.6 master from here and installed it on Joomla 3.0.3 (lastest stable release) and the comments (facebook, disquis and jcomment) aren't showing up? I'm running the website on 1and1 shared hosting environment. You can see the problem URL here: 
http://www.whyknottmanager.com/dgiwebsite/index.php/products/screen-printing 

Here is my system information:

PHP Built On    Linux infong 2.4 #1 SMP Thu Feb 14 13:02:49 CET 2013 i686 GNU/Linux
Database Version    5.1.67-log
Database Collation  utf8_general_ci
PHP Version     5.4.12
Web Server  Apache
WebServer to PHP Interface  cgi-fcgi
Joomla! Version     Joomla! 3.0.3 Stable [ Ember ] 04-February-2013 14:00 GMT
Joomla! Platform Version    Joomla Platform 12.2.0 Stable [ Neil Armstrong ] 21-September-2012 00:00 GMT
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:19.0) Gecko/20100101 Firefox/19.0 AlexaToolbar/alxf-2.17

**Comment by ntcreation** [comment]
I'm pretty sure this is not the place for asking for support... this is an issue reporter... but I'm new to GitHub so don't know where it should have gone.

Just a simple check - have you definitely set the options to show comments? It might not do so by default?

**Comment by whynotadv** [comment]
Hi Nathan,

I'm not asking for support, I'm reporting a bug. I tried several times to "Enable" the Comments for Facebook and Disquis and they aren't showing up in the lightbox. Plain and simple.
The download link from templaza.com is also corrupt it doesn't contain all the necessary installation files. See my attachments! Sonnie Le with Templaza told me this: 
"Please don't use "config" name. We use it to call param in administrator. Please try to re-install TZ Portfolio 3 and create a plugin with new name." BUT I didn't create ANY plugins and I tried reinstalling twice, I just installed the master file on Joomla 3.0.3 and everything works except comments! Plus customizing the appearance of information and elements (inside) the lightbox are really hard to override from the .less css file!

Thanks!

**Comment by templaza** [comment]
This problem was fixed in version 3.0.7.
Please download and reinstall it.

Thanks for use TZ Portfolio.
Sonle

**Comment by whynotadv** [comment]
Thank you Sonie!
